# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='lane',
            field=models.CharField(default=b'WestLane', max_length=256),
        ),
        migrations.AddField(
            model_name='parking',
            name='locality',
            field=models.CharField(default=b'Magarpatta', max_length=256),
        ),
    ]
